/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 asteroid.gltf 
Author: Mieke Roth (https://sketchfab.com/miekeroth)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/astroid-bennu-2926ad1b955a4d1982b88ebddba0a7be
Title: Astroid Bennu
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

function Asteroid(props) {
  const { nodes, materials } = useGLTF(`${import.meta.env.BASE_URL}models/asteroid/asteroid.gltf`)
  const meshRef = useRef();

  return (
    <group {...props} dispose={null}>
      <mesh ref={meshRef} geometry={nodes.Object_4.geometry} material={materials.Default_OBJ} />
      <mesh geometry={nodes.Object_5.geometry} material={materials.Default_OBJ} />
    </group>
  )
}

export default Asteroid;

useGLTF.preload(`${import.meta.env.BASE_URL}models/asteroid/asteroid.gltf`)