/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 earth.gltf 
Author: PatelDev (https://sketchfab.com/PatelDev)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/earth-f7a76c63ff1846afb2d606e5c8369c15
Title: Earth
*/

import React, { useRef, useEffect } from "react";
import { useGLTF } from "@react-three/drei";

function Earth({ onTargetSelect, selectedTarget }) {
  const { nodes, materials } = useGLTF(`${import.meta.env.BASE_URL}models/earth/earth.gltf`);
  const meshRef = useRef();

  useEffect(() => {
    const timer = setTimeout(() => {
      window.dispatchEvent(new Event('earthLoaded'));
    }, 100);
    return () => clearTimeout(timer);
  }, []);

  return (
    <group dispose={null}>
      <mesh
        ref={meshRef}
        geometry={nodes.Object_4.geometry}
        material={materials["Scene_-_Root"]}
        scale={1}
      />
    </group>
  );
}

export default Earth;

useGLTF.preload(`${import.meta.env.BASE_URL}models/earth/earth.gltf`)

